name: client
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.4
  http: ^0.13.4
  intl: ^0.17.0
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.1.1
  flutter_secure_storage: ^5.0.2
  image_picker: ^0.8.5+3
  flutter_svg: ^1.1.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
